### ISSUE TITLE
Problem with stopping on the "walls"

### ISSUE THREAD

**Issue by JakubZelek** [Iwomichu/probable-giggle#5]
**Describe the bug**
players with the same speed sometimes stop at the "walls" with different LEFT/RIGHT coordinates.

**To Reproduce**
1. start for example on the rigt side of map
2. give some left acceleration 
3. players stop sometimes at different positions

**Expected behavior**
players stop at the same LEFT/RIGHT position

**Comment by Iwomichu** [comment]
after a brief discussion, we realized that it is a problem with how space_game determines if object is at constraints. since the formula is:
`

    def is_at_constraints(self):
        new_x = self.x + self.horizontal_velocity
        new_y = self.y + self.vertical_velocity
        vertical_constraint = (new_y > self.y_constraint.min) and (new_y + self.height < self.y_constraint.max)
        horizontal_constraint = (new_x > self.x_constraint.min) and (new_x + self.width < self.x_constraint.max)
        return (not vertical_constraint) or (not horizontal_constraint)
`
it may happen that despite an object having some room left to the border of a screen, he cannot reach that border when having high velocity.

we also decided to not focus on this issue now, since its impact on game seem rather low - we will get back to it if future models would exploit this issue.
